image: node:0.12
services:
  - redis:2.8
before_script:
  - cd /builds/cayle/volos-redis-manager-cli
  - cp build_scripts/default.yaml test/demo/config/

test:
  script:
    - cd /builds/cayle/volos-redis-manager-cli
    - cat test/demo/config/default.yaml
    - env
    - npm install && npm test



