image: node:0.12
services:
  - redis:2.8
before_script:
  - cd /builds/cayle/volos-redis-manager-cli
  - npm install
  - cp build_scripts/default.yaml test/demo/config/

test:
  script:
    - cd /builds/cayle/volos-redis-manager-cli
    - npm test



